### ISSUE TITLE
Integration of IotWebConf?

### ISSUE THREAD

**Issue by emmrichd** [BojanJurca/Esp32_oscilloscope#10]
Hello,

I would like to use your very nice code to test some sensors, at home but also at other places.
For this, it would be really helpful, if I could change the wifi settings "on the fly", with a library like IotWebConf, for instance.
Have you ever thought of this? 

Kind Regards, Dieter

**Comment by BojanJurca** [comment]
Sure. Just change the code in network.h or provide your way of connecting to WiFi instead of calling startWiFi (); in setup ().
It should work. Let me know if you encounter any problems.

**Comment by BojanJurca** [comment]
I'm closing this issue.
