### ISSUE TITLE
FTP : 421 file system not mounted 

### ISSUE THREAD

**Issue by DumoulinPierre** [BojanJurca/Esp32_oscilloscope#18]
Hi, thanks for this project !

I have an issue at the step where we have to add some files to the ESP32 :

![Capture d’écran 2022-10-12 à 13 00 59](https://user-images.githubusercontent.com/20083973/195326023-c9447c16-5180-4b2c-a02f-b24e1a39e80c.png)

Thanks,
Pierre.

**Comment by BojanJurca** [comment]
Hm, I have just checked it again and it works as it should. Could you, please, give me some additional information like:

- did you change any code on your own?
- did you select a FATFS partition scheme prior to compiling and uploading sketch to Esp32?
- can you send me a console (COM) log?

Thank you.

Bojan

**Comment by BojanJurca** [comment]
By the way, if we will not be able to solve the file system problem for some reason there is a workarroud (made mainly for those Esp32 boards that do not have flash disk at all):
- take and compile RAM ONLY version otf the sketch that doesn't require a file system: https://github.com/BojanJurca/Esp32_oscilloscope/blob/master/Esp32_oscilloscope.ino%20RAM%20VERSION

Bojan

**Comment by DumoulinPierre** [comment]
Sorry, my bad, I was not doing the Partition Scheme step.. 
But it seems that my board (NodeMCU 32s) doesn't have this option.

I will try your RAM version :)

**Comment by DumoulinPierre** [comment]
It's working ! I have the html webpage :) 

thank's a lot for your time and reactivity !

**Comment by BojanJurca** [comment]
I'm glad I could help.

B.
