### ISSUE TITLE
Question: ESP32 wroom32

### ISSUE THREAD

**Issue by Zibri** [BojanJurca/Esp32_oscilloscope#20]
Is there a way to have a BIN file for ESP32 WROOM32?
Or a quick way to make one?

**Comment by BojanJurca** [comment]
Creating a BIN file shouldn't be difficult. Please see: https://randomnerdtutorials.com/bin-binary-files-sketch-arduino-ide/

You have to enter your WiFi credentials into code before creating a .BIN file, so they would be included.
