### ISSUE TITLE
ftp : 421 file system not mounted

### ISSUE THREAD

**Issue by megames07** [BojanJurca/Esp32_oscilloscope#25]
hello,
 
i get the error: Ftp : 421 file system not mounted. i have formatted it in fat.
Pls help

**Comment by BojanJurca** [comment]
Hi,

- which board are you using?
- which Tool | Partition Scheme are you using?
- can you send me the whole  Serial Monitor output since ESP32 starts?

**Comment by BojanJurca** [comment]
I'm closing this issue due to unresponsiveness.
