### ISSUE TITLE
WebSocket error: [object Event]

### ISSUE THREAD

**Issue by pierrebak** [BojanJurca/Esp32_oscilloscope#4]
Hello,

Thanks a lot for feedback Bojan: I will update the code, best wishes for 2021.
Thanks for the nice project.
I've been able to deploy the oscilloscope on the web server.
But nothing can be observed when activating a GPIO connecting to a PWN on Arduino: there is no wave observable at screen, activating the gpio seems ok as there is slight oscillations, but nothing chances if the GPIO is connectef to Arduino PWM

**Comment by BojanJurca** [comment]
Hello, I'm sorry for late reply, I somehow missed this issue. Please tell me more about what you are doing. Are you running oscilloscope on the same board as PWM you want to monitor or do you use two different boards?

**Comment by BojanJurca** [comment]
Oscilloscope was meant to monitor signals on the same ESP32 as your projects runs in the first place. Of course it can also be used to monitor external devices. Before using Oscilloscope you need to initialize pin mode of the pin that you are going to use by Oscilloscope. You can do this in Oscilloscope Arduino code (in setup () for example).

**Comment by BojanJurca** [comment]
Example:

void setup () {  
  Serial.begin (115200);

  /*
    ...
  */

  ledcSetup (0, 83, 10);  // channel 0, 83 Hz , 10 bit resolution (1024 values)
  ledcAttachPin (2, 0);   // attach pin 2 (built-in led) to channel 0

  ledcWrite (0, 307);     // PWM of built-in LED (channel 0 -> pin 2) with 1/3 of period (307 out of 1023)    
}

Then you can see:

![image](https://user-images.githubusercontent.com/42709677/103567811-c1635080-4ec4-11eb-9a36-029bb6547b59.png)

**Comment by BojanJurca** [comment]
I'm coding this issue. Please reopen it if this didn't solve your problem.
