### ISSUE TITLE
Formatting failed

### ISSUE THREAD

**Issue by lgomesfsp** [BojanJurca/Esp32_oscilloscope#5]
I am trying to install the oscilloscope but it is giving formatting error.

[        43] [file system] formatting, please wait ...
[        43] [file system] formatting failed.
[        44] [network] file system not mounted, can't read or write configuration files.

Can you help me ?

**Comment by BojanJurca** [comment]
I can't know for sure from your description. Most likely you haven't chosen the right partition schema in Arduino (Tools | Partition schema ...). You must choose one with FAT file system.

**Comment by BojanJurca** [comment]
I'm closing this issue, if the proposed solution is not OK, please reopen it.
